### ISSUE TITLE
SpinnerCircular not working

### ISSUE THREAD

**Issue by mukul-123** [adexin/spinners-react#11]
I used <SpinnerCircular/> in my js file of React and it doesn't show loader.
Please help.

**Comment by antonskrebetz** [comment]
> 

Everything works. how do you use the library as much detail as possible? Follow the instructions!

**Comment by adexin-team** [comment]
> I used in my js file of React and it doesn't show loader. Please help.

Please, give us more details. It works on our side.

**Comment by mukul-123** [comment]
Hey,
I was using in a wrong way.
Now, I made it correct.

Thanks.
