### ISSUE TITLE
Failed to parse source map WARNING

### ISSUE THREAD

**Issue by 96dervalics** [adexin/spinners-react#14]
I get the following warnings, when I `npm run` my react-app:
```
WARNING in ./node_modules/spinners-react/lib/esm/SpinnerCircular.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '[my-dir]\react\plebania\node_modules\spinners-react\src\SpinnerCircular.tsx' file: Error: ENOENT: no such file or directory, open '[my-dir]\react\plebania\node_modules\spinners-react\src\SpinnerCircular.tsx'
```
Same warning for these:
- SpinnerCircular.tsx
- SpinnerCircularFixed.tsx
- SpinnerCircularSplit.tsx
- SpinnerCircularSplit.tsx
- SpinnerDiamond.tsx
- SpinnerDotted.tsx
- SpinnerInfinity.tsx
- SpinnerRound.tsx
- SpinnerRoundFilled.tsx
- SpinnerRoundOutlined.tsx
- helpers.ts

The component works fine, and I didn't find any odd behavior but could you look into this problem?

**Comment by DrZanuff** [comment]
Same problem here.

**Comment by lucaspiresnabais** [comment]
+1

**Comment by jtoronto** [comment]
+1

**Comment by KumihoBG** [comment]
+1

**Comment by adexin-team** [comment]
Please, try v1.0.7.
