### ISSUE TITLE
How to set the background color to "transparent"?

### ISSUE THREAD

**Issue by sarchibald-mdsol** [adexin/spinners-react#18]

**Comment by sarchibald-mdsol** [comment]
I'd like to have the background color of the spinner be "transparent". Is there a way to do this?

**Comment by colin-chadwick** [comment]
Hey there! That works just like in CSS. Supply an RGBA color to the secondaryColor property, with the alpha channel set to 0. 

`<SpinnerCircular secondaryColor="rgba(0, 0, 0, 0)" />`
