### ISSUE TITLE
Size doesn't exist on SpinnerCircularFixed

### ISSUE THREAD

**Issue by mattfelten** [adexin/spinners-react#24]
`<SpinnerCircularFixed size={32} />` has a type error that `size` doesn't exist. It does seem to work though.

**Comment by Amit-K-007** [comment]
@mattfelten  `<SpinnerCircularFixed size={32} />` is working correctly. There is no any type error.

**Comment by mattfelten** [comment]
`spinners-react@1.0.7`

![CleanShot 2024-08-12 at 11 17 11](https://github.com/user-attachments/assets/e5058a3c-5ef0-4352-b592-255a049ef8f8)
> Type '{ size: number; thickness: number; speed: number; color: string; secondaryColor: "rgba(0, 0, 0, 0.44)"; className: string; "client:load": true; }' is not assignable to type 'IntrinsicAttributes & HTMLAttributes<SVGElement> & Partial<{ speed: number; still: boolean; thickness: number; }> & Partial<...>'.
  Property 'size' does not exist on type 'IntrinsicAttributes & HTMLAttributes<SVGElement> & Partial<{ speed: number; still: boolean; thickness: number; }> & Partial<...>'.ts(2322)

**Comment by Amit-K-007** [comment]
![image](https://github.com/user-attachments/assets/53cd949b-804e-4d55-b7c4-412305cf727e)
I tried using the same component as you, and it worked properly for me. 
It might help to try reinstalling the library, as this could resolve the error.

**Comment by mattfelten** [comment]
Really odd. You're right. I can't replicate it on CodeSandbox. https://codesandbox.io/p/sandbox/test-react-spinners-zf2nph

I did reinstall all my dependencies but didn't change anything. I'll keep digging but seems like the library is fine. Must be on my end somewhere.
